### ISSUE TITLE
Landing Page Frontend

### ISSUE THREAD

**Issue by hsorathia** [hsorathia/DavinProject#14]
Need to have a front end for the landing page that introduces users to the website and prompts them to register, there should also be a button for signing in (if they already have an account).

**Comment by hsorathia** [comment]
By our next meeting Davin will have done the basic UI for the landing page.

Take a look at these links for inspiration (on incognito so you're not auto logged in)
- https://www.facebook.com/
- https://github.com/
See how there's a description of the site, a prompt for users to register, and there's either a sign in button (and/or signup button)

To accomplish this refer to [this](https://www.robinwieruch.de/react-semantic-ui-tutorial) guide on how to create a log-in page. You're probably not going to copy this word for word because we want a different implementation this.

By the next meeting you should have a draft of the landing and login/sign-up pages.

**Comment by Innocent-Fear** [comment]
May need to add css stuff but otherwise its good for now
